import React from 'react';
import * as styles from './style/style.module.scss';
import characterImg from '../../assets/character/toukaYoko99.jpg';
export const HomePage = () => {
    const title = 'Touka YokoHame [Yoko] E[sc]apeX';
    return <div className={styles.page}><h2 className={styles.title}>{title}</h2>
        <p className={styles.info}>Touka YokoHame wants to escape on moto from the villains. Help her stay alive.</p>
        <div><img alt='image of hope' src={characterImg}></img></div>
        <p>All characters, objects and events in the game are fictional. All coincidences are accidental. Whole images was generated by AI YandexART 2.0</p>
    </div>
}